Repository Arquisoft/wichat_en2a, pull requests merged in 2025-04, with the labels that each got.

#111 Redone previously done work
  docker-compose.yml
  gatewayservice/gateway-service.js
  gatewayservice/gateway-service.test.js
  questionservice/question-service.js
  questionservice/question-service.test.js
  webapp/package-lock.json
  webapp/package.json
Labels: duplicate

#98 Documentation of the API
  gatewayservice/openapi.yaml
Labels: documentation

#135 Fixed/Supressed warnings for CI and CD
  webapp/package-lock.json
  webapp/src/App.js
  webapp/src/components/Game.js
  webapp/src/components/Timer.js
Labels: github actions, front-end, deployment

#138 Change the UI of Login page.
  webapp/src/components/Login.js
  webapp/src/components/Login.test.js
Labels: front-end

#143 Fixes in Game page
  webapp/src/components/Game.js
  webapp/src/components/Game.test.js
Labels: front-end

#147 Login and AddUser view refactor
  webapp/src/App.test.js
  webapp/src/components/AddUser.js
  webapp/src/components/AddUser.test.js
  webapp/src/components/AuthForm.js
  webapp/src/components/Login.js
  webapp/src/components/Login.test.js
Labels: front-end

#139 Added Different Game Modes
  gatewayservice/gateway-service.js
  gatewayservice/gateway-service.test.js
  llmservice/llm-service.js
  llmservice/llm-serviceEmpathy.test.js
  questionservice/question-service.js
  questionservice/question-service.test.js
  webapp/package-lock.json
  webapp/package.json
  webapp/public/car.png
  webapp/public/dinosaur.png
  webapp/public/flag.png
  webapp/public/painting.png
  webapp/public/place.png
  webapp/public/questionMark.png
  webapp/public/star.png
  webapp/src/App.js
  webapp/src/components/CustomGameMode.js
  webapp/src/components/CustomGameMode.test.js
  webapp/src/components/Game.js
  webapp/src/components/Game.test.js
  webapp/src/components/GameModes.js
  webapp/src/components/GameModes.test.js
  webapp/src/components/GameOver.js
  webapp/src/components/Home.js
  webapp/src/components/Home.test.js
  webapp/src/components/Navbar.js
  webapp/src/components/Navbar.test.js
  webapp/src/components/game-styles.css
Labels: enhancement

#141 Addition of TopScores and improvement of Leaderboard and Scores
  gatewayservice/gateway-service.js
  gatewayservice/gateway-service.test.js
  users/gameservice/game-service.js
  users/gameservice/game-service.test.js
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.js
  webapp/src/components/Leaderboard.js
  webapp/src/components/Leaderboard.test.js
  webapp/src/components/LeaderboardComponents.js
  webapp/src/components/LeaderboardComponents.test.js
  webapp/src/components/Navbar.js
  webapp/src/components/Navbar.test.js
  webapp/src/components/Scores.js
  webapp/src/components/Scores.test.js
  webapp/src/components/TopScores.js
  webapp/src/components/TopScores.test.js
Labels: enhancement, front-end

#154 Added the remote server and fixed some endpoints' documentation
  gatewayservice/openapi.yaml
Labels: documentation

#159 Question loading rework
  .github/workflows/build.yml
  .github/workflows/release.yml
  docker-compose.yml
  docs/src/04_solution_strategy.adoc
  docs/src/09_architecture_decisions.adoc
  gatewayservice/gateway-service.js
  gatewayservice/gateway-service.test.js
  gatewayservice/openapi.yaml
  llmservice/llm-service.js
  llmservice/llm-serviceEmpathy.test.js
  llmservice/llm-serviceErrors.test.js
  llmservice/llm-serviceGemini.test.js
  questionservice/question-service.js
  questionservice/question-service.test.js
  schedulingservice/.dockerignore
  schedulingservice/Dockerfile
  schedulingservice/package-lock.json
  schedulingservice/package.json
  schedulingservice/scheduling-service.js
  schedulingservice/scheduling-service.test.js
  sonar-project.properties
  webapp/src/components/CustomGameMode.js
  webapp/src/components/CustomGameMode.test.js
  webapp/src/components/Game.js
  webapp/src/components/Game.test.js
  webapp/src/components/GameModes.js
  webapp/src/components/GameModes.test.js
Labels: front-end, back-end, deployment

#166 Added jmeter test plan used for load tests and some local results
  loadtests/results/local-10-users.pdf
  loadtests/results/local-100-users.pdf
  loadtests/results/local-1000-users.pdf
  loadtests/results/local-20-users.pdf
  loadtests/results/local-50-users.pdf
  loadtests/results/local-500-users.pdf
  loadtests/users.csv
  loadtests/wichat_en2a_load_tests.jmx
Labels: documentation

#160 Administration page and corresponding changes
  gatewayservice/gateway-service.js
  gatewayservice/gateway-service.test.js
  gatewayservice/package.json
  llmservice/package.json
  users/authservice/auth-model.js
  users/authservice/auth-service.js
  users/authservice/auth-service.test.js
  users/authservice/package.json
  users/userservice/package.json
  users/userservice/user-model.js
  users/userservice/user-service.js
  users/userservice/user-service.test.js
  webapp/package.json
  webapp/src/App.js
  webapp/src/components/AdminPanel.js
  webapp/src/components/AdminPanel.test.js
  webapp/src/components/AuthContext.js
  webapp/src/components/Login.js
Labels: enhancement, front-end, back-end
