Repository Arquisoft/wichat_en2a, pull requests merged in 2025-03, with the labels that each got.

#36 Modified section 9 to avoid redundancy with Wiki
  docs/src/09_architecture_decisions.adoc
Labels: documentation

#48 Score, Game and Leaderboard Service implementation
  users/userservice/game-service.js
  users/userservice/game-service.test.js
  users/userservice/leaderboard-service.js
  users/userservice/leaderboard-service.test.js
  users/userservice/score-model.js
  users/userservice/user-model.js
  users/userservice/user-service.js
  users/userservice/user-service.test.js
  webapp/public/leaderboard.html
  webapp/src/App.js
  webapp/src/components/Leaderboard.js
  webapp/src/components/Leaderboard.test.js
Labels: enhancement

#44 Llmservice incorrect options feature
  llmservice/llm-service.js
  llmservice/llm-service.test.js
Labels: enhancement

#54 Enhanced Login And Registration
  webapp/src/App.js
  webapp/src/App.test.js
  webapp/src/components/AddUser.js
  webapp/src/components/AddUser.test.js
Labels: enhancement

#45 Documentation enhancement
  docs/src/04_solution_strategy.adoc
Labels: documentation

#59 Incorrect answers generated by LLM in gatewayservice
  questionservice/package-lock.json
  questionservice/package.json
  questionservice/question-service.js
  questionservice/question-service.test.js
Labels: enhancement

#83 Fixed the communication issues
  docker-compose.yml
  questionservice/question-service.js
Labels: enhancement

#87 Improvements in the quality of the code for quesion-service
  questionservice/question-service.js
  questionservice/question-service.test.js
Labels: SonarQube

#88 Added question service to be taken into account when deploying
  .github/workflows/release.yml
Labels: bug, github actions

#94 Replace onNavigate with react-router navigation logic
  .gitignore
  webapp/package-lock.json
  webapp/package.json
  webapp/src/App.js
  webapp/src/App.test.js
  webapp/src/components/AddUser.js
  webapp/src/components/AddUser.test.js
  webapp/src/components/Game.js
  webapp/src/components/Game.test.js
  webapp/src/components/Home.js
  webapp/src/components/Home.test.js
  webapp/src/components/Leaderboard.js
  webapp/src/components/Leaderboard.test.js
  webapp/src/components/Login.js
  webapp/src/components/Login.test.js
  webapp/src/components/Navbar.js
  webapp/src/components/Navbar.test.js
  webapp/src/index.js
Labels: bug, enhancement

#97 Update GitHub actions and SonarQube to include all services
  .github/workflows/build.yml
  .github/workflows/release.yml
  sonar-project.properties
  users/gameservice/user-model.js
Labels: SonarQube, github actions

#99 Frontend home improved
  webapp/public/questionMark.webp
  webapp/src/App.js
  webapp/src/App.test.js
  webapp/src/components/Home.js
  webapp/src/components/Home.test.js
  webapp/src/components/Navbar.js
  webapp/src/components/Navbar.test.js
Labels: enhancement

#101 Updates in front end before second deliverable
  package-lock.json
  questionservice/question-service.js
  users/gameservice/package-lock.json
  webapp/src/App.js
  webapp/src/components/Game.js
  webapp/src/components/Game.test.js
  webapp/src/components/GameOver.js
  webapp/src/components/GameOver.test.js
  webapp/src/components/Timer.js
  webapp/src/components/Timer.test.js
Labels: enhancement

#102 Update on documentation
  docs/src/04_solution_strategy.adoc
Labels: documentation

#104 Joining the changes of the LLM with the chat
  llmservice/llm-service.js
Labels: enhancement

#106 Refined the Prompt and added a "Memory" to the LLM
  llmservice/llm-service.js
Labels: enhancement

#100 Rework of Question Service
  docker-compose.yml
  gatewayservice/gateway-service.js
  gatewayservice/gateway-service.test.js
  questionservice/question-service.js
  questionservice/question-service.test.js
  users/userservice/user-service.test.js
  webapp/src/components/Leaderboard.js
Labels: enhancement
