Repository Arquisoft/wichat_en2a, pull requests merged in 2025-05, with the labels that each got.

#155 Grafana Implementation
  gatewayservice/gateway-service.js
  gatewayservice/monitoring/grafana/provisioning/dashboards/Wichat_en2a.json
  gatewayservice/monitoring/prometheus/prometheus.yml
  gatewayservice/package-lock.json
  gatewayservice/package.json
Labels: enhancement

#179 Solved some issues with error handling
  gatewayservice/gateway-service.js
  gatewayservice/gateway-service.test.js
  questionservice/question-service.js
  schedulingservice/scheduling-service.js
  schedulingservice/scheduling-service.test.js
Labels: bug, back-end

#181 Adding more E2E tests
  webapp/e2e/features/edit-user.feature
  webapp/e2e/features/game.feature
  webapp/e2e/features/leaderboards.feature
  webapp/e2e/features/logout.feature
  webapp/e2e/features/my-scores.feature
  webapp/e2e/features/register-form.feature
  webapp/e2e/features/top-scores.feature
  webapp/e2e/steps/edit-user.steps.js
  webapp/e2e/steps/game.steps.js
  webapp/e2e/steps/leaderboards.steps.js
  webapp/e2e/steps/logout.steps.js
  webapp/e2e/steps/my-scores.steps.js
  webapp/e2e/steps/register-form.steps.js
  webapp/e2e/steps/top-scores.steps.js
  webapp/src/components/Navbar.js
Labels: enhancement, deployment

#196 Fix documentation (from presentation)
  docs/images/TechnicalContext.png
  docs/src/03_context_and_scope.adoc
Labels: documentation
